import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Exam App",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="text-3xl text-red-500 text-center py-4">
          auth layout
        </header>
        {children}
      </body>
    </html>
  );
}
